"""Audit item F4 (operator half): the Teams drawer, source-contract style.

Mirrors ``tests/integration/test_display_drawer_contract.py`` and
``tests/integration/test_data_folder.py::OperatorControlTests``: these assert
against the operator source files rather than a browser, proving the markup
and script carry the right shape without needing a webview. The U-001 visual
fit (the identity stripe never causing overflow) and the actual confirm/apply
round trip against a stub bridge are Playwright checks run by hand and
recorded in the implementation report, not something a source-text assertion
can prove.
"""

from __future__ import annotations

import unittest
from pathlib import Path

VIEWS = Path(__file__).resolve().parents[2] / "src" / "scoreboard" / "views"


class TeamsDrawerContractTests(unittest.TestCase):
    def setUp(self) -> None:
        self.html = (VIEWS / "operator" / "index.html").read_text(encoding="utf-8")
        self.js = (VIEWS / "operator" / "operator.js").read_text(encoding="utf-8")

    def _tools_bar(self) -> str:
        tools = self.html.split('<footer class="tools">', 1)[1]
        return tools.split("</footer>", 1)[0]

    def _teams_drawer(self) -> str:
        drawer = self.html.split('<div class="drawer" id="teams-drawer"', 1)[1]
        return drawer.split('<div class="drawer" id="setup-drawer"', 1)[0]

    def test_the_tool_bar_offers_a_teams_button(self) -> None:
        tools = self._tools_bar()
        self.assertIn('data-action="open_teams"', tools)
        self.assertIn('id="open-teams"', tools)

    def test_teams_drawer_exists_and_holds_the_form_ids(self) -> None:
        self.assertIn('id="teams-drawer"', self.html)
        drawer = self._teams_drawer()

        self.assertIn('id="team-list"', drawer)
        self.assertIn('id="team-form"', drawer)
        self.assertIn('id="team-name-input"', drawer)
        self.assertIn('id="team-short-input"', drawer)
        self.assertIn('id="team-primary-input"', drawer)
        self.assertIn('id="team-secondary-input"', drawer)
        self.assertIn('data-action="save_team"', drawer)
        self.assertIn('data-action="prefill_team" data-team="home"', drawer)
        self.assertIn('data-action="prefill_team" data-team="away"', drawer)
        self.assertIn('id="home-identity-swatch"', drawer)
        self.assertIn('id="home-identity-short"', drawer)
        self.assertIn('id="away-identity-swatch"', drawer)
        self.assertIn('id="away-identity-short"', drawer)

    def test_the_drawers_static_html_carries_no_data_command(self) -> None:
        """The apply buttons are generated by the script, not written by hand."""

        drawer = self._teams_drawer()
        self.assertNotIn("data-command", drawer)

    def test_the_board_carries_an_identity_stripe_for_each_side(self) -> None:
        self.assertIn('id="home-identity-stripe"', self.html)
        self.assertIn('id="away-identity-stripe"', self.html)

    def test_the_new_text_and_colour_inputs_are_drafts(self) -> None:
        """Every ``<input>`` in this drawer must carry ``data-draft="true"``.

        ``tests/integration/test_bridge.py`` enforces this for the whole page;
        this test pins it locally so a regression is caught by this file too.
        """

        drawer = self._teams_drawer()
        for field_id in (
            "team-name-input",
            "team-short-input",
            "team-primary-input",
            "team-secondary-input",
        ):
            with self.subTest(field=field_id):
                start = drawer.index(f'id="{field_id}"')
                tag = drawer[max(0, start - 40): start + 200]
                self.assertIn('data-draft="true"', tag)

    def test_the_script_calls_the_three_bridge_methods(self) -> None:
        self.assertIn("api.teams()", self.js)
        self.assertIn("api.save_team(", self.js)
        self.assertIn("api.delete_team(", self.js)

    def test_generated_apply_buttons_use_set_team_name(self) -> None:
        self.assertIn("'data-command', 'set_team_name'", self.js)

    def test_argumentsfor_reads_the_dataset_name(self) -> None:
        arguments_for = self.js.split("function argumentsFor(button)", 1)[1]
        arguments_for = arguments_for.split("\n  function fieldValue", 1)[0]
        self.assertIn("button.dataset.name", arguments_for)

    def test_close_drawers_names_the_teams_drawer(self) -> None:
        close_drawers = self.js.split("function closeDrawers()", 1)[1].split("}", 1)[0]
        self.assertIn("'teams-drawer'", close_drawers)

    def test_no_set_team_name_string_is_built_from_anything_but_a_preset_name(self) -> None:
        """The only place ``data-name`` is written is from ``team.name``."""

        build_row = self.js.split("function buildTeamRow(team)", 1)[1]
        build_row = build_row.split("\n  /* --- Where the game is saved", 1)[0]

        self.assertIn("setAttribute('data-name', team.name)", build_row)
        # And nowhere in the whole script is a preset name assembled from
        # anything else (a typed field, a computed value, and so on).
        self.assertNotIn("data-name', team.short_name", self.js)


if __name__ == "__main__":
    unittest.main()
